apiVersion: v1
kind: Service
metadata:
  name: hw-prueba-gha-service
spec:
  selector:
    app: hello-world-prueba-gha
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort  # Cambiado a NodePort para Minikube
