on: push
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build and push to docker
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: "prueba-gha"  # Cambia "nombre-personalizado" por el nombre que desees
        tag_with_ref: true
        tag_with_sha: true  # Corregí el nombre de la opción
        tags: ${{ github.sha }}
